### ISSUE TITLE
Crashes if not a git repo

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-fileexplorer#169] opened 2017-11-27 19:07 UTC
The app crashes if it isn't a git repo (i.e., doesn't have the `.git/` directory). This may need to be resolved if going forward with RPM packaging.

**Comment by brianmcmichael** [comment] 2017-11-27 21:40
This is caused by the use of gitsync
https://github.com/OSC/ood-fileexplorer/blob/master/app.js#L12

This could be resolved with error handling, or with embedding the version number elsewhere in the app, although in the case of the latter we'll need to remember to keep it updated.

**Closed** 2017-12-19 20:05 UTC
Labels: bug
